### ISSUE TITLE
action fails intermittently

### ISSUE THREAD

**Issue by ReenigneArcher** [hugo19941994/auto-datfile-generator#8]
Any idea why the upload assets/create release step of the action is failing occasionally? I am having the same issue in my fork.

**Comment by hugo19941994** [comment]
No idea. I've forked the step repo and changed a few things. I'll try and see if it works these days. Overriding assets also stopped working though. It might be easier to change to another action. https://github.com/softprops/action-gh-release seems popular

**Comment by ReenigneArcher** [comment]
I knew about the overriding assets failure... I changed mine to create a new release with the current timestamp. Not ideal as there is a new release each day, but better than failing.

I'll look into using another action. The one you linked looks promising.

**Comment by ReenigneArcher** [comment]
That action worked, at least on the first attempt. Will keep an eye on it to see if it's more stable. See here for my config if you'd like (https://github.com/RetroArcher/RetroArcher.dats/blob/master/.github/workflows/daily_build.yml)

P.S. I think that one also has an issue with the overriding existing releases. There is an open PR to address the issue, which I believe checks if the same release already exists, if so it deletes it before creating a new one.

Appreciate the support!

**Comment by ReenigneArcher** [comment]
Hello friend! I found an action that seems to be able to update the release assets of an existing release. I tried several different actions actually and they all had issues with updating assets. Most of them gave fairly cryptic error messages, but the one below gave more detailed error messages. What I found was it was failing because of the parenthesis in the file names. Perhaps this was the cause all along. In any event, I think I will stick with the release action below as it seems to be updated very regularly, issues are taken care of quickly.

https://github.com/ncipollo/release-action

```yaml
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            name: Nightly
            tag: Nightly
            artifacts: "*.xml,*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            body: Released by github actions
            commit: master
```

Also, had to make some tweaks to the no-intro.py as datamatic made some minor changes for when no captcha is presented.
